import { ThemeContextWrapper } from "@/Context/ThemeContext";
import StoreProvider from "./StoreProvider";
import MainTamplate from "./MainTamplate";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <MainTamplate>{children}</MainTamplate>
        </StoreProvider>
      </body>
    </html>
  );
}
